# Theme settings
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Settings
locale:	"en-US"
title:	"Help the Helper"
subtitle: "Thoughts and projects regarding numbers, basketball, and medicine"
url: "bigmonty12.github.io" 
twitter_username: bigmonty12
github_username:  bigmonty12
name: "Austin Montgomery"
words_per_minute: 200

# Site Author
author:
   name: "Austin Montgomery"
   avatar: "/assets/photos/montgomery_headshot.jpeg"
   bio: "Former college basketball player. Future physician-scientist."
   location: "Salt Lake City, UT"
   links:
     - label: "Email"
       icon: "fas fa-fw fa-envelope-square"
       url: mailto:austinbrucemontgomery@gmail.com
     - label: "Twitter"
       icon: "fab fa-fw fa-twitter-square"
       url: "https://twitter.com/bigmonty12"
     - label: "GitHub"
       icon: "fab fa-fw fa-github"
       url: "https://github.com/bigmonty12?tab=repositories" 

# Site Footer
footer:
   links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bigmonty12"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bigmonty12?tab=repositories" 

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
use_math: true

titles_from_headings:
   enabled:	true
   strip_title:	true
   collections:	true

# Conversion
highlighter: rouge
markdown: kramdown
kramdown:
   math_engine: katex
   input: GFM
   auto_ids: true
   hard_wrap: false
   syntax_highlighter: rouge

defaults:
   # _posts
   - scope:
      path: ""
      type: posts
     values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
   # _pages
   - scope:
      path: ""
      type: pages
     values:
      layout: single
      author_profile: true

# Reading Files
include:
   - .htaccess
   - _pages
exclude:
   - Rakefile
   - package.json
   - package-lock.json
   - assets/js/plugins
   - assets/js/_main.js
   - assets/js/vendor
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass/SCSS
sass:
   sass_dir: _sass
   style: compressed

# Outputting
permalink: /:categories/:title
paginate: 5
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
