title: Help the Helper
email: austinbrucemontgomery@gmail.com
description: Pseudorandom thoughts about basketball, medicine, and numbers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "bigmonty12.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bigmonty12
github_username:  bigmonty12
# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
